---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: httpd
        state: present
    - name: Start Apache server
      service:
        name: httpd
        state: started
    - name: Add firewall rules
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
